review
gemini-testing/playwright-oauth pull request #2
Opened 2023-06-15 13:08 UTC by rprovodenko

2023-06-15 13:19 UTC, KuznetsovRoman commented on package.json
> +    "license": "UNLICENSED",
MIT

2023-06-15 13:20 UTC, KuznetsovRoman commented on .npmrc
> +save-exact = true
Зачем?

2023-06-15 13:25 UTC, KuznetsovRoman commented on src/testtoken
> +mytesttoken123
Это не исходный код, такого не должно быть на гитхабе

2023-06-15 13:29 UTC, KuznetsovRoman commented on src/init.test.ts
> +        await init({ tokenFilePath: join(__dirname, "./testtoken") });
Тут нужно замокать fs.promises.readFile, чтобы этот метод с аргументами `"./testtoken", { encoding: "utf-8" }` возвращал какое-то постоянное значение (`foo`), и потом уже проверять, что в `process.env. SELENIUM_REMOTE_HEADERS` поставилось правильное значение - чтений с файловой системы в юнит тестах не должно быть

Еще этот тест негерметичный. Нужно сохранить изначальное состояние `process.env`, затем установить какое-то `process.env.SELENIUM_REMOTE_HEADERS` самостоятельно, а потом, после теста, вернуть все как было. Такой тест может рандомно пройти, потому что предыдущий записал `{"Authorization":"OAuth mytesttoken123"}` в `process.env.SELENIUM_REMOTE_HEADERS`

2023-06-15 13:40 UTC, KuznetsovRoman commented on src/read-token.ts
> +        throw new Error(`Token found at ${path} is empty`);
Этих токенов в проекте может быть очень много, и по такому тексту ошибки с первого взгляда и не понятно, какой вообще токен искался

Предлагаю текст ошибки сделать более понятным, что-то типа `Playwright OAuth token at ${path} is empty`

2023-06-15 13:47 UTC, KuznetsovRoman commented on src/init.ts
> +    process.env.SELENIUM_REMOTE_HEADERS = `{"Authorization":"OAuth ${token}"}`;
С этим могут возникнуть проблемы.

Допустим, нам понадобилось в `remote selenium` прокидывать еще один хедер, и мы написали для этого другую `fixture`. После того, как эта новая `fixture` что-то положила в `process.env.SELENIUM_REMOTE_HEADERS`, эта функция перезапишет все хедеры.

Тут нужно проверить, является ли это поле валидным ЖСОНом до перезаписи. Если да, то распарсить, добавить в него поле `Authorization` с токеном, и положить обратно уже обогащенный сериализованный жсон.

2023-06-15 13:53 UTC, rprovodenko commented on .npmrc
> +save-exact = true
скопировал из другого нашего репо. если это не наш бест практис - удалю

2023-06-15 13:54 UTC, rprovodenko commented on package.json
> +        "typescript": "^5.1.3"
видимо save exact добавил позже. нам с крышечкой или без?)

2023-06-15 13:57 UTC, rprovodenko commented on src/init.test.ts
> +    it("should load token from file and into environment", async () => {
не совсем. можно добавить into "the" environment, но не обязательно (артикли могут пропускаться в названиях вещей, в заголовках статей и тп). к file "the" не нужно. into звучит лучше чем to

2023-06-15 14:00 UTC, KuznetsovRoman commented on .npmrc
> +save-exact = true
Не нашел таких наших репо, где оно есть (hermione, html-reporter, hermione-storybook, hermione-mocks...).

2023-06-15 14:01 UTC, KuznetsovRoman commented on package.json
> +        "typescript": "^5.1.3"
С крышечкой (кроме редких исключений, где пакет не следует семверу, но тут вроде таких нет)

2023-06-15 14:03 UTC, rprovodenko commented on src/init.ts
> +    process.env.SELENIUM_REMOTE_HEADERS = `{"Authorization":"OAuth ${token}"}`;
я про это подумал, но появилось подозрение что `SELENIUM_REMOTE_HEADERS` только для этого будет использоваться. но да, хотя-бы по неймингу, не только для этого. окей, изменю

2023-06-15 14:07 UTC, rprovodenko commented on .npmrc
> +save-exact = true
https://github.com/gemini-testing/hermione-oauth/blob/master/.npmrc

2023-06-15 20:30 UTC, KuznetsovRoman commented on .npmrc
> +save-exact = true
А, ну этому репо почти год. Я бы на другие смотрел, более свежие, как раз из списка того, что я перечислил

2023-06-15 20:32 UTC, KuznetsovRoman commented on src/testtoken
> +mytesttoken123
Просто этого, как и в принципе чтения файлов, можно избежать, замокав метод из `fs`. Тогда этот файл становится не нужен

2023-06-16 09:15 UTC, DudaGod requested changes
Есть вопросы

2023-06-16 09:15 UTC, DudaGod commented on src/read-token.ts
> +    const token = await readFile(path, { encoding: "utf-8" });
Тут на самом деле можно просто синхронно прочитать.

И не учитывается кейс, что файла может не быть. В этом случае нужно кинуть понятную ошибку и докинуть в нее `help` если пользователь указал.

2023-06-16 09:15 UTC, DudaGod commented on tsconfig.json
> +        "types": ["node"]
Тут явно можно не указывать

2023-06-16 09:15 UTC, DudaGod commented on tsconfig.spec.json
> +        "types": ["node", "jest"]
И здесь тоже

2023-06-16 09:15 UTC, DudaGod commented on tsconfig.common.json
> +        "target": "es2017",
Можно уже на `es2021` переходить

2023-06-16 09:15 UTC, DudaGod commented on src/read-token.ts
> +}
Нет тестов на этот файл.

2023-06-16 09:52 UTC, rprovodenko commented on src/read-token.ts
> +    const token = await readFile(path, { encoding: "utf-8" });
> Тут на самом деле можно просто синхронно прочитать.
синхронное ИО это всегда антипаттерн в ноде

2023-06-16 10:14 UTC, rprovodenko commented on .gitignore
> +build
мы не собираем тесты, мы ts-jest юзаем

2023-06-16 10:59 UTC, rprovodenko commented on README.md
> +export default globalSetup;
Это просто пример в ридми, взятый из доков playwright. Предлагаю, пусть юзер сам решает как ему экспортировать

2023-06-16 11:02 UTC, rprovodenko commented on src/index.ts
> +export * from "./init";
не люблю когда в index.ts есть логика. На более сложных проектах, если оставлять логику в индексе, получается грязно.

2023-06-16 11:10 UTC, rprovodenko commented on package.json
> +        "@typescript-eslint/eslint-plugin": "^5.59.11",
https://typescript-eslint.io/getting-started/#step-1-installation

как я понимаю в `plugins` подсасывается

2023-06-16 11:44 UTC, KuznetsovRoman commented on src/init.ts
> +    process.env.SELENIUM_REMOTE_HEADERS = `{"Authorization":"OAuth ${token}"}`;
Тут еще про регистр нужно не забыть

2023-06-16 11:44 UTC, rprovodenko commented on src/init.ts
> +    const path = options?.tokenFilePath ?? join(homedir(), ".playwright/oauth_token");
https://github.com/gemini-testing/hermione-oauth/blob/master/src/index.ts#L15
а если токен начинается с `/`?

2023-06-19 07:03 UTC, rprovodenko commented on src/init.ts
> +    process.env.SELENIUM_REMOTE_HEADERS = `{"Authorization":"OAuth ${token}"}`;
мне кажется лучше ворнинг кидать и ничего не делать

2023-06-19 08:33 UTC, rprovodenko commented on src/read-token.ts
> +}
тестируется в другом файле

2023-06-19 10:31 UTC, rprovodenko commented on src/init.ts
> +    const path = options?.tokenFilePath ?? join(homedir(), ".playwright/oauth_token");
Я не понимаю, почему аргумент `token` - обязательный, когда у тебя еще есть опция передать через окружение `PLAYWRIGHT_OAUTH_TOKEN`?

2023-06-19 11:30 UTC, DudaGod commented on src/init.ts
> +    const path = options?.tokenFilePath ?? join(homedir(), ".playwright/oauth_token");
Ну да, получается должно быть опциональным. У нас для таких целей в hermione используется `configparser` - https://github.com/gemini-testing/configparser. Он под капотом сам понимает выставлена в итоге опция через cli, env, api или нет. Тут конечно можно без него обойтись, тем более что pwt не дает возможность добавлять свои cli опции.

2023-06-19 12:20 UTC, closed without merging